using System.Threading.Tasks;
using RazorLight;

namespace RazorMailMessage.TemplateBase
{
    public class DefaultTemplateBase<T> : TemplatePage<T>
    {
        public override Task ExecuteAsync()
        {
            // Overridden by compiled templates generated by RazorLight
            return Task.CompletedTask;
        }
    }
}
